### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by patricktresp** [react-native-community/react-native-blur#130]
Hi,

after struggling w/ adding all needed lines in settings.gradle, build.gradle and MainApplication.java i finally could compile the android project.
But when testing on Device i get following Fatal Error:

`Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
       at com.fivehundredpx.android.blur.BlurringView.initializeRenderScript(BlurringView.java:98)
       at com.fivehundredpx.android.blur.BlurringView.<init>(BlurringView.java:37)
       at com.fivehundredpx.android.blur.BlurringView.<init>(BlurringView.java:26)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:24)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:11)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[zip file "/data/app/com.spockstar.mobile-2/base.apk"],nativeLibraryDirectories=[/data/app/com.spockstar.mobile-2/lib/x86, /data/app/com.spockstar.mobile-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.fivehundredpx.android.blur.BlurringView.initializeRenderScript(BlurringView.java:98)
       at com.fivehundredpx.android.blur.BlurringView.<init>(BlurringView.java:37)
       at com.fivehundredpx.android.blur.BlurringView.<init>(BlurringView.java:26)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:24)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:11)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

what is the actual issue? can you help me on that?

**Comment by tommyschmiedel** [comment]
I think the issue is that you cannot pass children to BlurView on Android. Checkout the basic Android example here: https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic/index.android.js

**Comment by patricktresp** [comment]
ah i see, 
happy Platform switch! 
Thanks alot!

**Comment by tommyschmiedel** [comment]
Also see this issue: #99
