### ISSUE TITLE
Crashing my android application

### ISSUE THREAD

**Issue by SeunLanLege** [react-native-community/react-native-blur#252]
`adb logcat` reveals

```bash
12-26 23:38:32.116   632   651 I ActivityManager: Displayed com.vesnet/.MainActivity: +898ms
12-26 23:38:32.305  9038  9065 V WebViewFactory: webViewPackageName: com.android.webview
12-26 23:38:32.305  9038  9065 I WebViewFactory: Loading com.android.webview version 44.0.2403.119 (code 246011910)
12-26 23:38:32.425  9038  9065 W System  : ClassLoader referenced unknown path: /system/app/webview/lib/x86
12-26 23:38:32.460  9038  9065 I LibraryLoader: Time to load native libraries: 16 ms (timestamps 6443-6459)
12-26 23:38:32.461  9038  9065 I LibraryLoader: Expected native library version number "",actual native library version number ""
12-26 23:38:32.471  9038  9065 W art     : Attempt to remove non-JNI local reference, dumping thread
12-26 23:38:32.853  9038  9064 I ReactNativeJS: Running application "Vesnet" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
12-26 23:38:34.426  9038  9064 W ReactNativeJS: Warning: Failed prop type: The prop `viewRef` is marked as required in `BlurView`, but its value is `undefined`.
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in BlurView (at baseContainer.js:55)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in BaseContainer (at signup.js:14)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in SignUpUI (at SceneView.js:31)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in SceneView (at CardStack.js:423)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at createAnimatedComponent.js:134)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in AnimatedComponent (at Card.js:26)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Card (at PointerEventsContainer.js:55)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Container (at CardStack.js:454)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at CardStack.js:383)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at CardStack.js:382)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in CardStack (at CardStackTransitioner.js:97)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at Transitioner.js:192)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Transitioner (at CardStackTransitioner.js:49)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in CardStackTransitioner (at StackNavigator.js:60)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Unknown (at createNavigator.js:52)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Navigator (at createNavigationContainer.js:210)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in NavigationContainer (at index.js:22)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in Provider (at index.js:18)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in App (at renderApplication.js:35)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at AppContainer.js:102)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in RCTView (at View.js:112)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in View (at AppContainer.js:122)
12-26 23:38:34.426  9038  9064 W ReactNativeJS:     in AppContainer (at renderApplication.js:34)
12-26 23:38:34.853  9038  9038 D AndroidRuntime: Shutting down VM
12-26 23:38:34.858  9038  9038 E AndroidRuntime: FATAL EXCEPTION: main
12-26 23:38:34.858  9038  9038 E AndroidRuntime: Process: com.vesnet, PID: 9038
12-26 23:38:34.858  9038  9038 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.cmcewen.blurview.BlurringView.initializeRenderScript(BlurringView.java:110)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.cmcewen.blurview.BlurringView.<init>(BlurringView.java:41)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.cmcewen.blurview.BlurringView.<init>(BlurringView.java:30)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:28)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:11)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1010)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:981)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[zip file "/data/app/com.vesnet-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vesnet-1/lib/x86, /data/app/com.vesnet-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	... 24 more
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: android.support.v8.renderscript.RenderScript
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 		... 25 more
12-26 23:38:34.858  9038  9038 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-26 23:38:34.861   632   643 W ActivityManager:   Force finishing activity com.vesnet/.MainActivity

```

**Comment by SeunLanLege** [comment]
`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;`

this appears to be the culprit, not entirely sure why or how.

**Comment by lpb006** [comment]
do you solve this problem?

**Comment by lpb006** [comment]
@SeunLanLege   do you solve this problem?

**Comment by RomanISWG** [comment]
Same problem here and the solution above does not work vor me.

**Comment by Sotatek-HieuDuong** [comment]
> vim android/app/build.gradle, add
> 
> ```
>          renderscriptTargetApi 20
>          renderscriptSupportModeEnabled true
> ```
> 
> to defaultConfig

Thanksss. it save my day :D
