### ISSUE TITLE
Canot install via yarn or npm

### ISSUE THREAD

**Issue by DataGreed** [react-native-community/react-native-blur#318]
# Bug

Command

```
$ yarn add @react-native-community/blur --verbose
```

gives the following result:

```
yarn add v1.3.2
(node:57277) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
verbose 0.599 Checking for configuration file "/Users/username/Work/Breakfast App/breakfast-app/.npmrc".
verbose 0.6 Checking for configuration file "/Users/username/.npmrc".
verbose 0.6 Found configuration file "/Users/username/.npmrc".
verbose 0.601 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.601 Checking for configuration file "/Users/username/Work/Breakfast App/breakfast-app/.npmrc".
verbose 0.602 Checking for configuration file "/Users/username/Work/Breakfast App/.npmrc".
verbose 0.602 Checking for configuration file "/Users/username/Work/.npmrc".
verbose 0.602 Checking for configuration file "/Users/username/.npmrc".
verbose 0.602 Found configuration file "/Users/username/.npmrc".
verbose 0.603 Checking for configuration file "/Users/.npmrc".
verbose 0.606 Checking for configuration file "/Users/username/Work/Breakfast App/breakfast-app/.yarnrc".
verbose 0.607 Checking for configuration file "/Users/username/.yarnrc".
verbose 0.607 Found configuration file "/Users/username/.yarnrc".
verbose 0.607 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.607 Checking for configuration file "/Users/username/Work/Breakfast App/breakfast-app/.yarnrc".
verbose 0.608 Checking for configuration file "/Users/username/Work/Breakfast App/.yarnrc".
verbose 0.608 Checking for configuration file "/Users/username/Work/.yarnrc".
verbose 0.608 Checking for configuration file "/Users/username/.yarnrc".
verbose 0.608 Found configuration file "/Users/username/.yarnrc".
verbose 0.609 Checking for configuration file "/Users/.yarnrc".
verbose 0.613 current time: 2019-06-18T22:51:52.092Z
[1/4] 🔍  Resolving packages...
verbose 1.079 Performing "GET" request to "https://registry.yarnpkg.com/react-native-community%2fblur".
verbose 1.996 Request "https://registry.yarnpkg.com/react-native-community%2fblur" finished with status code 405.
verbose 1.998 Error: Received malformed response from registry for undefined. The registry may be down.
    at /Users/username/.yarn/lib/cli.js:48907:15
    at Generator.next (<anonymous>)
    at step (/Users/username/.yarn/lib/cli.js:92:30)
    at /Users/username/.yarn/lib/cli.js:110:14
    at new Promise (<anonymous>)
    at new F (/Users/username/.yarn/lib/cli.js:29389:28)
    at /Users/username/.yarn/lib/cli.js:89:12
    at Function.findVersionInRegistryResponse (/Users/username/.yarn/lib/cli.js:48946:7)
    at /Users/username/.yarn/lib/cli.js:48963:28
    at Generator.next (<anonymous>)
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Same problem with NPM:

```
$ npm install --save --verbose @react-native-community/blur
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   '--verbose',
npm verb cli   '@react-native-community/blur' ]
npm info using npm@6.5.0-next.0
npm info using node@v11.6.0
npm verb npm-session 933c27f47022e7d1
npm http fetch GET 200 https://registry.npmjs.org/@react-native-community%2fblur 23ms (from cache)
npm timing stage:loadCurrentTree Completed in 2833ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 15ms
npm http fetch GET 304 https://registry.npmjs.org/@pusher%2fchatkit-client 1054ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/@react-native-community%2fasync-storage 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/babel-plugin-transform-decorators-legacy 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/flow-bin 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/jest 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/metro-react-native-babel-preset 5ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/moment-timezone 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-mixin 11ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native 24ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-actioncable 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-background-geolocation 5ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-blur 4ms (from cache)
npm WARN deprecated react-native-blur@3.2.2: WARNING: This project has been renamed to @react-native-community/blur. Install using @react-native-community/blur instead.
npm http fetch GET 200 https://registry.npmjs.org/react-native-circular-progress 5ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-device-info 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-email-link 5ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-fbsdk 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-gesture-handler 6ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-gifted-chat 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-haptic-feedback 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-i18n 12ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-iap 7ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-image-picker 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-interactable 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-keyboard-done-button 2ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-maps 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-modal 15ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-permissions 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-push-notification 5ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-reanimated 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-sentry 11ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-shake 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-snap-carousel 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-splash-screen 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-svg 12ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-swiper 3ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-native-vector-icons 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-navigation 13ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-navigation-fluid-transitions 4ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/react-navigation-is-focused-hoc 4ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 4887ms
npm verb stack TypeError: Cannot read property 'match' of undefined
npm verb stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
npm verb stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
npm verb stack     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm verb stack     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm verb stack     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
npm verb stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm verb stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at processImmediate (timers.js:632:19)
npm verb cwd /Users/username/Work/Breakfast App/breakfast-app
npm verb Darwin 18.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--verbose" "@react-native-community/blur"
npm verb node v11.6.0
npm verb npm  v6.5.0-next.0
npm ERR! Cannot read property 'match' of undefined
npm verb exit [ 1, true ]
npm timing npm Completed in 6017ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2019-06-18T22_56_25_046Z-debug.log
```

## Environment info

React native info output:

```bash
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
      Memory: 23.37 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.3.2 - ~/.yarn/bin/yarn
      npm: 6.5.0-next.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26
        Build Tools: 23.0.1, 24.0.2, 25.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Android TV Intel x86 Atom, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2.2 AI-145.3537739
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.0-rc.0 => 0.59.0-rc.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: ?

**Comment by a-koka** [comment]
We need the latest code released to npm. The only way to use this with react-native 0.60 is to use the master branch for now.
