### ISSUE TITLE
Example can't  run correctly

### ISSUE THREAD

**Issue by Damoness** [react-native-community/react-native-blur#344]
# Bug

1. git clone https://github.com/react-native-community/react-native-blur.git
2. cd react-native-blur/example
3.npm install
4.react-native run-ios

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/wudi/Work/Learning/ReactNative/rn/react-native-blur/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

## Environment info

![image](https://user-images.githubusercontent.com/5622121/68992806-a3dfbb80-08ab-11ea-8f53-6b99a6abc76a.png)

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by chengsam** [comment]
Try running `npm install` also in the `react-native-blur` directory, then run `npm run start --reset-cache` to start the bundler, and run `react-native run-ios` again.
