### ISSUE TITLE
3.4.1版本在安卓上闪退

### ISSUE THREAD

**Issue by cindyya** [react-native-community/react-native-blur#356]
在安卓上第一次渲染出来了，但是滑动页面后，会出现闪退；错误日志如下：
02-13 16:18:06.468 8220-8220/io.chaoge.door E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.chaoge.door, PID: 8220
    android.renderscript.RSInvalidStateException: Calling RS with no Context active.
        at android.renderscript.RenderScript.validate(RenderScript.java:1062)
        at android.renderscript.Allocation.copyFrom(Allocation.java:739)
        at com.cmcewen.blurview.BlurringView.blur(BlurringView.java:160)
        at com.cmcewen.blurview.BlurringView.onDraw(BlurringView.java:73)
        at android.view.View.draw(View.java:15122)
        at android.view.View.updateDisplayListIfDirty(View.java:14056)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
        at android.view.View.draw(View.java:15125)
        at android.view.View.updateDisplayListIfDirty(View.java:14056)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
        at android.view.View.draw(View.java:15125)
        at android.view.View.updateDisplayListIfDirty(View.java:14056)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
        at android.view.View.updateDisplayListIfDirty(View.java:14051)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at android.view.View.draw(View.java:15125)
        at android.widget.FrameLayout.draw(FrameLayout.java:592)
        at android.widget.ScrollView.draw(ScrollView.java:1689)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:442)
        at android.view.View.updateDisplayListIfDirty(View.java:14056)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
        at android.view.View.draw(View.java:15125)
        at android.view.View.updateDisplayListIfDirty(View.java:14056)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.View.draw(View.java:14846)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
        at android.view.View.updateDisplayListIfDirty(View.java:14051)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
        at android.view.View.updateDisplayListIfDirty(View.java:14016)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
        at android.view.View.updateDisplayListIfDirty(View.java:14016)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
        at android.view.View.updateDisplayListIfDirty(View.java:14016)
        at android.view.View.getDisplayList(View.java:14079)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
        at android.view.View.updateDisplayListIfDirty(View.java:14016)

**Comment by cindyya** [comment]
1
