### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: android.renderscript.ScriptIntrinsicBlur

### ISSUE THREAD

**Issue by haddad-yacine** [react-native-community/react-native-blur#370]
# Bug

## Environment info
- Brand: samsung
- Model: Galaxy Core
- Orientation: Portrait
- Available RAM memory: 112.42 MB
- Available disk space: 2.53 GB 
- Operating system
- Version: 4.1.2
- Orientation: Portrait
- Rooted: No

`react-native info` output:

```bash
 - react: 16.9.0 => 16.9.0
 - react-native: 0.61.5 => 0.61.5
```

Library version: 3.4.1

## stack trace
```bash
 Fatal Exception: java.lang.NoClassDefFoundError: android.renderscript.ScriptIntrinsicBlur
       at com.cmcewen.blurview.BlurringView.initializeRenderScript(BlurringView.java:111)
       at com.cmcewen.blurview.BlurringView.<init>(BlurringView.java:41)
       at com.cmcewen.blurview.BlurringView.<init>(BlurringView.java:30)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:30)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:12)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:82)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:269)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:972)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:943)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:524)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by fonov** [comment]
Same error

```
Fatal Exception: java.lang.NoClassDefFoundError: android.renderscript.ScriptIntrinsicBlur
       at eightbitlab.com.blurview.RenderScriptBlur.<init>(RenderScriptBlur.java)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java)
       at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.addRootView(NativeViewHierarchyManager.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:524)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

 Galaxy S3 Mini, android 4.1.2

**Comment by fonov** [comment]
probably this is fixed the problem https://github.com/react-native-community/react-native-blur/issues/252#issuecomment-355718720
