### ISSUE TITLE
Android: App crashes on startup even if not used

### ISSUE THREAD

**Issue by neXorianus** [react-native-community/react-native-blur#393]
# Bug report

## Summary

After installing this plugin everything works fine in iOS, but android crashes on app start and logcat spamming lots of warnings and the following error:
```
08-19 14:00:16.425 10854 10854 E AndroidRuntime: FATAL EXCEPTION: main
08-19 14:00:16.425 10854 10854 E AndroidRuntime: Process: package.name, PID: 10854
08-19 14:00:16.425 10854 10854 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{package.name/package.name.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "package.name.MainActivity" on path: DexPathList[[zip file "/data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/base.apk"],nativeLibraryDirectories=[/data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/lib/x86, /data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "package.name.MainActivity" on path: DexPathList[[zip file "/data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/base.apk"],nativeLibraryDirectories=[/data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/lib/x86, /data/app/package.name-J5Hp7u9bVqdxXsZv3ZcqOQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
08-19 14:00:16.425 10854 10854 E AndroidRuntime: 	... 9 more
```
Even if i do not actually import BlurView into my code, android crashes.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 160.62 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.14.2 - ~/.npm/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 28.0.1, 28.0.2, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6200805
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version:  "@react-native-community/blur": "^3.6.0",

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

**Comment by ezranbayantemur** [comment]
First, if you installed your app on your device, uninstall it via `adb uninstall <your app package name>`
Then clean the gradle `cd android && ./gradlew clean && cd .. `

and you should able to run your app.

_Note: In Windows it's `gradlew` not `./gradlew`_

**Comment by neXorianus** [comment]
Since reporting this issue i removed the plugin completely.
I will reinstall and have a look, if that helps

**Comment by ammoradi** [comment]
@neXorianus did you find any other solution to have blur feature?

**Comment by neXorianus** [comment]
> @neXorianus did you find any other solution to have blur feature?

i didn't get to reinstall the plugin until yet - so i dropped the bluriness in my app

**Comment by ph98** [comment]
Thanks 
Cleaning gradlew and running again fixed my problem

> First, if you installed your app on your device, uninstall it via `adb uninstall <your app package name>`
> Then clean the gradle `cd android && ./gradlew clean && cd .. `
> 
> and you should able to run your app.
> 
> _Note: In Windows it's `gradlew` not `./gradlew`_
