### ISSUE TITLE
eightbitlab.com.blurview.BlockingBlurController.b java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by brunoaduarte** [react-native-community/react-native-blur#397]
# Bug report

## Summary

```
eightbitlab.com.blurview.BlockingBlurController.b

java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:437)
  at android.view.ViewGroup.getAndVerifyPreorderedView (ViewGroup.java:4468)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4984)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23193)
  at android.view.View.draw (View.java:23062)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw (ReactViewGroup.java:3)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at com.facebook.react.ReactRootView.dispatchDraw (ReactRootView.java)
  at android.view.View.draw (View.java:23060)
  at android.view.ViewGroup.drawChild (ViewGroup.java:5230)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4987)
  at android.view.View.draw (View.java:23193)
  at eightbitlab.com.blurview.BlockingBlurController.b (BlockingBlurController.java:49)
  at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw (BlockingBlurController.java:2)
  at android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:1102)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:3310)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2200)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:9065)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:999)
  at android.view.Choreographer.doCallbacks (Choreographer.java:797)
  at android.view.Choreographer.doFrame (Choreographer.java:732)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:984)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
```

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 2.04 GB / 31.92 GB
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-15 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 14.0.2
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0
    react-native: ~0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 0.62.2

## Steps to reproduce

Describe what you expected to happen:

1. …
2. …

## Reproducible sample code

```
  return (
    
    <SafeAreaView style={styles.safeAreaContainer}>
      {isLoading ? <ActivityIndicator /> : (
        <FlatList
            style={styles.list}
            ListEmptyComponent={listEmptyComponent.bind(this)}
            refreshing={isRefreshing}
            onRefresh={() => getData(true)}
            data={data}
            renderItem={renderNumberItem}
            extraData={dataUpdated} // This state is used to trigger a flatList re-render
        />
      )}

      { settings.subscription == 'INVALID' ? 
      <View style={[StyleSheet.absoluteFill, styles.nonBlurredContent]}>
        <BlurView style={[StyleSheet.absoluteFill, styles.nonBlurredContent]} blurType="light" blurAmount={1} reducedTransparencyFallbackColor="white" />
        <Text style={styles.blurText}>No valid subscription found.</Text>
      </View> : null
      }

    </SafeAreaView>
  )
```

**Comment by jlandrum** [comment]
In my case I'm seeing this when it tries to blur a FlatList:
`java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3624)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4110)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20210)
	at android.view.View.draw(View.java:20077)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20210)
	at android.view.View.draw(View.java:20077)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
	at android.view.View.draw(View.java:20075)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw(View.java:20210)
	at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.j
	at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2474)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`
It appears that for Android, it renders all children views to a bitmap?

**Comment by bobsmits** [comment]
I got the same error in my firebase crashlytics. In my case it seem to happen when i'm switching back to the app from another activity. I there already a workaround or fix for this?

**Comment by santiagorodriguezequinox** [comment]
Hi People I don't use this library but i had the exactly same error in my react native application when I tested on Android physical devices. 
And remove the elevation prop from styles solves it.

**Comment by KaviduAloka** [comment]
> Hi People I don't use this library but i had the exactly same error in my react native application when I tested on Android physical devices.
> And remove the elevation prop from styles solves it.

This solved the case. Thanks

**Comment by maulikdhameliya** [comment]
please use this in package.json. It worked for me . Looks like master branch has the fix.
`"@react-native-community/blur": "git+https://github.com/Kureev/react-native-blur.git",`
