### ISSUE TITLE
App crashing on Android

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [react-native-community/react-native-blur#71]
Java log:

```
E/AndroidRuntime( 4472): Process: com.bountify, PID: 4472
E/AndroidRuntime( 4472): java.lang.OutOfMemoryError: Failed to allocate a 4194316 byte allocation with 3912916 free bytes and 3MB until OOM
E/AndroidRuntime( 4472):    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime( 4472):    at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 4472):    at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
E/AndroidRuntime( 4472):    at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
E/AndroidRuntime( 4472):    at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java:81)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.decoder.ImageDecoder.decodeStaticImage(ImageDecoder.java:128)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:94)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
E/AndroidRuntime( 4472):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 4472):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 4472):    at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
E/AndroidRuntime( 4472):    at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  768):   Force finishing activity com.bountify/.MainActivity
```

How to reproduce:
I have a listView where I render components that use BlurView
I go to another route (therefore rendering another screen)
I go back to the screen where I have the listView
I scroll the listView a little bit and baaam it crashes

React Native 0.28
Genymotion Android 5.0.0 (API 21)

**Comment by sampurcell93** [comment]
This is a common error in Android development, especially when using React Native for Android. The fact that you're using BlurView on Images in a ListView suggests to me that you're not dequeuing cells that go out of bounds, and since images are memory-heavy, you're running out of space super fast.

**Comment by rafaelcorreiapoli** [comment]
How can I solve this?

**Comment by sampurcell93** [comment]
Sigh.... I have a private copy of a somewhat fixed ListView implementation that dequeues offscreen cells, seen [here](https://github.com/facebook/react-native/issues/5688#issuecomment-220628601). Read my instructions and check out the gist.

I am not really familiar with this package, but I can imagine blur being memory intensive.

**Comment by cmcewen** [comment]
@rafaelcorreiapoli did the modified list view work for you?

**Comment by Kureev** [comment]
Closed due to lack of feedback from the TS.
